// <auto-generated />
using hbeauty.aspnetcore2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace hbeauty.aspnetcore2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20170919125146_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("hbeauty.aspnetcore2.Models.ServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name_Chs");

                    b.Property<string>("Name_Cht");

                    b.Property<string>("Name_Eng");

                    b.HasKey("Id");

                    b.ToTable("ServiceItem");
                });

            modelBuilder.Entity("hbeauty.aspnetcore2.Models.ServiceItemImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("ServiceItemId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.ToTable("ServiceItemImage");
                });

            modelBuilder.Entity("hbeauty.aspnetcore2.Models.ServiceItemVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("ServiceItemId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.ToTable("ServiceItemVideo");
                });

            modelBuilder.Entity("hbeauty.aspnetcore2.Models.ServiceItemImage", b =>
                {
                    b.HasOne("hbeauty.aspnetcore2.Models.ServiceItem", "ServiceItem")
                        .WithMany("Images")
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("hbeauty.aspnetcore2.Models.ServiceItemVideo", b =>
                {
                    b.HasOne("hbeauty.aspnetcore2.Models.ServiceItem", "ServiceItem")
                        .WithMany("Videos")
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
